kind: pipeline
name: default

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:
    registry: hub.docker.com
    repo: mdicloud/nginx-helloworld
    tags: latest
    cache: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

